/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencimientosRouteImport } from './routes/vencimientos'
import { Route as PolizasRouteImport } from './routes/polizas'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as ComisionesRouteImport } from './routes/comisiones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaptacionRouteImport } from './routes/captacion'
import { Route as IndexRouteImport } from './routes/index'

const VencimientosRoute = VencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const PolizasRoute = PolizasRouteImport.update({
  id: '/polizas',
  path: '/polizas',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComisionesRoute = ComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptacionRoute = CaptacionRouteImport.update({
  id: '/captacion',
  path: '/captacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captacion': typeof CaptacionRoute
  '/clientes': typeof ClientesRoute
  '/comisiones': typeof ComisionesRoute
  '/facturacion': typeof FacturacionRoute
  '/polizas': typeof PolizasRoute
  '/vencimientos': typeof VencimientosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captacion': typeof CaptacionRoute
  '/clientes': typeof ClientesRoute
  '/comisiones': typeof ComisionesRoute
  '/facturacion': typeof FacturacionRoute
  '/polizas': typeof PolizasRoute
  '/vencimientos': typeof VencimientosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captacion': typeof CaptacionRoute
  '/clientes': typeof ClientesRoute
  '/comisiones': typeof ComisionesRoute
  '/facturacion': typeof FacturacionRoute
  '/polizas': typeof PolizasRoute
  '/vencimientos': typeof VencimientosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captacion'
    | '/clientes'
    | '/comisiones'
    | '/facturacion'
    | '/polizas'
    | '/vencimientos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captacion'
    | '/clientes'
    | '/comisiones'
    | '/facturacion'
    | '/polizas'
    | '/vencimientos'
  id:
    | '__root__'
    | '/'
    | '/captacion'
    | '/clientes'
    | '/comisiones'
    | '/facturacion'
    | '/polizas'
    | '/vencimientos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptacionRoute: typeof CaptacionRoute
  ClientesRoute: typeof ClientesRoute
  ComisionesRoute: typeof ComisionesRoute
  FacturacionRoute: typeof FacturacionRoute
  PolizasRoute: typeof PolizasRoute
  VencimientosRoute: typeof VencimientosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencimientos': {
      id: '/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof VencimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polizas': {
      id: '/polizas'
      path: '/polizas'
      fullPath: '/polizas'
      preLoaderRoute: typeof PolizasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comisiones': {
      id: '/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof ComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captacion': {
      id: '/captacion'
      path: '/captacion'
      fullPath: '/captacion'
      preLoaderRoute: typeof CaptacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptacionRoute: CaptacionRoute,
  ClientesRoute: ClientesRoute,
  ComisionesRoute: ComisionesRoute,
  FacturacionRoute: FacturacionRoute,
  PolizasRoute: PolizasRoute,
  VencimientosRoute: VencimientosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
